# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
      PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_USER: ${{ secrets.PG_USER }}
      APP_KEY: ${{ secrets.APP_KEY }}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
    
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kanban-adonis-testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 'install dependencies'
      run: npm ci

    - name: 'run tests'
      run: npm test

    - name: 'build app'
      run: npm run build
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${ { secrets.KNOWN_HOSTS }} 
    - name: Execute test Script
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER }} ls
